const messages = {
    en: {
        message: {
            hello: 'hello world'
        },
        nav: {
            title1: 'Smile in the Sky',
            title2: 'Prospective Design',
            title3: 'Refreshing Experience',
            title4: 'Cabin Classes',
            title5: 'Video',
            title6: '抽獎活動',
        },
        index: {
            title: '妳好',
            kv_tw_sun: "../images/en-sun.png",
            kv_tw_air: "../images/en-air.png",
            kv_tw_water: "../images/en-water.png",
            kvslogn_tw: "../images/kv-en-slogn.png",
            about: {
                title1: '更多長榮787夢幻客機介紹',
                title2: 'A Dream in the Sky',
                btn1: '外型介紹',
                btn2: '360°介紹',
                txt: 'The Boeing 787 Dreamliner affords the most comfortable flight experience with its cutting-edge aerodynamic technology, lighter composite materials.',
                list_title1: 'Wings that Smile',
                list_title2: 'Flight Stability',
                list_title3: 'Egg-Shaped Noise Reduction Nozzle',
                list_title4: 'Energy Conservation and Carbon Reduction',
                list_txt1: 'The wings of the 787 are made of light, flexible carbon fiber composite materials, which can withstand a greater intensity of fluctuations than conventional aircraft wings. The smooth raked wingtip reduces in-flight air drag and conserves fuel.',
                list_txt2: 'With its more flexible carbon fiber wings, the 787 has superior stabilization performance in turbulence compared to conventional aircraft. The gust suppression system automatically adjusts wing surface, reducing motion in the cabin in-flight and significantly improving flight stability when turbulence is detected.',
                list_txt3: 'The latest egg-shaped chevron nozzle design allows a smoother mixing process for the cold and hot air streams in the engine and effectively reduces in-flight airflow noise.',
                list_txt4: 'The lighter composite materials effectively reduce the weight of the aircraft. The 787’s advanced aerodynamic technology and onboard systems, paired with high-performance Genx engines, conserve 20% to 25% of fuel and carbon emissions.',
            },
            feature: {
                title1: 'Refreshing Experience',
                front_title1: '../images/pic-en-sun.png',
                front_title2: '../images/pic-en-air.png',
                front_title3: '../images/pic-en-water.png',
                front_txt1: 'With the largest windows in the sky and five levels of digital tinting, the Boeing 787 Dreamliner has more natural light and amazing views from every seat in the plane.',
                front_txt2: 'The Boeing 787 hits the sweet spot equivalent to 6,000ft of cabin altitude and adds advanced air filtration systems to bring a new cabin experience that reduces symptoms of fatigue, jet-lag and headaches.',
                front_txt3: 'The new high tech carbon composite fuselage of the Boeing 787 enables an optimum humidity level that is four times higher than other planes. More moisture means more comfort with reduced irritation and dehydration.',
                back_title1: '更大的舷窗面積',
                back_title2: '液晶體調節進光',
                back_title3: '更有效控制艙壓',
                back_title4: '機艙更保濕',
                back_txt1: '787採用業界最大面積舷窗，較A350增加40%、A330增加78%的窗戶面積，增加飛行時的採光及視野。',
                back_txt2: '不需遮陽板，只要透過按鈕，即可5段式調校窗戶顏色與進光量、減少窗外射入的眩光。',
                back_txt3: '相較傳統民航機艙壓在海拔8,000呎，787機身材質可將艙壓控制在海拔6,000呎，有助於減輕暈機不適，並提高血液含氧量。',
                back_txt4: '傳統民航機採用鋁合金材質，容易在濕潤的環境下產生腐蝕，所以會將機艙濕度保持在約4~7%，以增加機身使用壽命；787機身由於採用抗腐蝕的複合材質，能提升機艙濕度高達10~15%。',
            },
            classinfo: {
                title1: 'Cabin Classes',
                btn1: 'Royal Laurel Class',
                btn2: 'Economy Class',
                block1_title1: 'EVA Air’s All New Boeing 787 Business Class features a cross-disciplinary collaboration with the design director of BMW Designworks to release brand new EVA Air Royal Laurel Class.',
                block1_title2: 'A Global Business Cabin',
                block1_title3: 'A Modern, Tailored, & Private Seat',
                block1_title4: '現代感的色系搭配',
                block1_txt1: 'EVA Air & BMW Designworks, in a cross-disciplinary collaboration, introduce the brand new EVA Air Royal Laurel Class.',
                block1_txt2: 'Designed around the core concepts of the space and brand, the tailor-made seating perfectly fits the business class cabin, offering contemporary colors, woven material in harmony with overall cabin visuals, and 23-inch-wide full lie-flat seats.',
                block1_txt3: 'Emphasizing width and horizontal space, seats are designed to naturally integrate passenger privacy, service functionality, operational convenience and storage space, to fully meet each passenger’s needs.',
                block1_txt4: '座椅選用舒適的頂級材質，搭配完美的色系呈現當代的工藝質感。',
                block1_list1: 'Full Lie-Flat Seats',
                block1_list2: 'Storage Space',
                block1_list3: 'Large One-Piece Tray Table',
                block1_list4: '18“ Full HD Display',
                block1_list5: 'Seat Control Panel',
                block1_list6: 'Supplementary Seat Control Panel',
                block1_list7: 'Reading Light',
                block1_list8: 'Retractable Partition',
                block1_list9: 'Mood Light',
                block1_list10: 'Aisle Indicators',
                block1_list11: 'Starlight Lighting',
                block1_list1_txt: 'Designed for comfort and ease of use, our modern, minimal linear design, featuring custom-made, high-quality pure wool seat covers paired with natural leather pillows, gives you an unparalleled tactile experience.',
                block1_list2_txt: 'Spaces for personal item storage let passengers enjoy a worry-free flight experience.',
                block1_list3_txt: 'The one-piece, non-folding tray table with rotational design is very easy to use. The side counter space is designed to offer a more flexible way to enjoy a meal or work.',
                block1_list4_txt: 'The world`s most advanced eX3 in-flight digital entertainment system offers an exclusive, luxurious entertainment experience.',
                block1_list5_txt: 'An integrated power outlet and remote control, featuring intuitive symbols and an accessible size that is very user-friendly.',
                block1_list6_txt: 'Installed on the side at a lower position to facilitate access when reclining.',
                block1_list7_txt: 'The exclusive reading light to the side of the seat offers the most comfortable environment for both reading and resting.',
                block1_list8_txt: 'Offers personal space.',
                block1_list9_txt: 'The adjustable mood light system creates an enchanting atmosphere.',
                block1_list10_txt: 'The information display on the outer side of the aisle shows the seat number, the upright indicator and the do-not-disturb indicator.',
                block1_list11_txt: 'The world’s first Boeing 787 with starlight lighting. In combination with the light blue color, it creates the scintillating sensation of a starry night sky.',
                block2_list1: 'Adjustable Head & Neck Support',
                block2_list2: '12" FULL HD Display',
                block2_list3: 'Power Outlet',
                block2_list4: 'Spacious Seating',
                block2_list5: 'Cabin Mood Light',
                block2_list1_txt: 'The head rest can be adjusted vertically up to 6 inches, with 6 different adjustment directions, and it is equipped with a neck support design that fits passengers of different heights.',
                block2_list2_txt: 'The world`s latest eX3 in-flight digital entertainment system with a 12" full HD display offers an exclusive, high-quality entertainment experience.',
                block2_list3_txt: 'Available for a variety of AC plugs, to support all your business or entertainment needs. (Except in the first row, the cabin is equipped with 2 outlets for every 3 seats.)',
                block2_list4_txt: 'Recaro seats from Germany with an ultrathin structural design offer a wider and more comfortable seating space.',
                block2_list5_txt: 'The amber lighting during mealtimes creates a romantic candlelit ambiance. When you want to rest, the soft lighting transition effect, paired with a blue skyline and twinkling stars. Different modes create a supremely relaxed cabin environment.',
            },
            btn_close: "Close",
        }
    },

    zh_tw: {
        message: {
            hello: 'こんにちは、世界'
        },
        nav: {
            title1: '天空的微笑',
            title2: '前瞻設計',
            title3: '全新體驗',
            title4: '艙等設備',
            title5: '介紹影片',
            title6: '抽獎活動',
        },
        index: {
            title: '妳好',
            kv_tw_sun: "../images/tw-sun.png",
            kv_tw_air: "../images/tw-air.png",
            kv_tw_water: "../images/tw-water.png",
            kvslogn_tw: "../images/kv-slogn.png",
            about: {
                title1: '更多長榮787夢幻客機介紹',
                title2: '來自天空的夢幻客機',
                btn1: '外型介紹',
                btn2: '360°介紹',
                txt: '787使用更輕量的複合材料與前瞻性空氣動力技術，創造最舒適的飛行體驗。',
                list_title1: '微笑曲線機翼',
                list_title2: '強化飛行穩定性',
                list_title3: '降低噪音的蛋殼造型發動機',
                list_title4: '節能減碳',
                list_txt1: '787機翼採用輕薄強韌的碳纖維複合材質，可比傳統客機的機翼承受更劇烈的氣流變化；翼尖向後圓滑彎曲的上帆角，可降低飛行時的空氣阻力，進而降低油耗。',
                list_txt2: '更有彈性的碳纖維材質機翼，比傳統客機更能緩和不穩定氣流造成的影響；全新垂直風切抑制系統，在偵測到亂流時，會自動調整機翼操控面，減輕機艙搖晃程度，大幅提升飛行穩定性。',
                list_txt3: '最新發動機外殼設計(CHEVRON)，使發動機冷熱氣流混合過程更為平順，有效降低飛行時所產生的氣流噪音。',
                list_txt4: '運用更輕的複合物料，有效減低機身重量；先進的空氣動力學技術及飛機系統，配置效能較高的Genx發動機，787較傳統客機減少20~25%之油耗與碳排放產生。',
            },
            feature: {
                title1: '特色介紹',
                front_title1: '../images/pic-sun.png',
                front_title2: '../images/pic-air.png',
                front_title3: '../images/pic-water.png',
                front_txt1: '787使用業界最大舷窗， 以液晶體5段式調節窗戶明暗，讓您自在享受雲端美景。',
                front_txt2: '相較傳統客機艙壓為海拔8,000呎，787可將艙壓控制在海拔6,000呎，相對提升血液含氧量，有效減輕暈機徵狀。',
                front_txt3: '機身採用抗腐蝕複合材質，得以提高較傳統客機近4倍的艙內濕度，緩和乾燥帶來的不適。',
                back_title1: '更大的舷窗面積',
                back_title2: '液晶體調節進光',
                back_title3: '更有效控制艙壓',
                back_title4: '機艙更保濕',
                back_txt1: '787採用業界最大面積舷窗，較A350增加40%、A330增加78%的窗戶面積，增加飛行時的採光及視野。',
                back_txt2: '不需遮陽板，只要透過按鈕，即可5段式調校窗戶顏色與進光量、減少窗外射入的眩光。',
                back_txt3: '相較傳統民航機艙壓在海拔8,000呎，787機身材質可將艙壓控制在海拔6,000呎，有助於減輕暈機不適，並提高血液含氧量。',
                back_txt4: '傳統民航機採用鋁合金材質，容易在濕潤的環境下產生腐蝕，所以會將機艙濕度保持在約4~7%，以增加機身使用壽命；787機身由於採用抗腐蝕的複合材質，能提升機艙濕度高達10~15%。',
            },
            classinfo: {
                title1: '艙等介紹',
                btn1: '皇璽桂冠艙',
                btn2: '經濟艙',
                block1_title1: '跨界攜手推出全新皇璽桂冠艙',
                block1_title2: '全球化商務客艙',
                block1_title3: '新穎及客製化的座椅',
                block1_title4: '現代感的色系搭配',
                block1_txt1: '全新長榮航空波音787皇璽桂冠艙，跨界攜手 BMW Designworks首席設計師，以空間、品牌為理念核心，跳脫傳統印象，客製化座椅環境從水平化設計出發，以現代色系與編織材質調和艙內視覺，打造寬達23吋的全平躺座椅。',
                block1_txt2: '以空間感及品牌為核心，跳脫傳統思維，將客製化座椅融入整體客艙環境，以穩重低調的色系，創造更寬敞的空間感受。',
                block1_txt3: '強調座椅寬度和水平空間，將旅客的隱私性，服務的功能性，操作的便利性及收納空間的規劃自然融入座椅設計，全方位滿足旅客的需求。',
                block1_txt4: '座椅選用舒適的頂級材質，搭配完美的色系呈現當代的工藝質感。',
                block1_list1: '全平躺正向交錯式排列座椅',
                block1_list2: '個人置物空間',
                block1_list3: '大尺寸單片式餐桌',
                block1_list4: '18吋FULL HD螢幕',
                block1_list5: '座椅控制面板',
                block1_list6: '輔助座椅控制面板',
                block1_list7: '座椅閱讀燈',
                block1_list8: '可收納隔板',
                block1_list9: '情境燈光系統(Mood Light)',
                block1_list10: '走道指示燈',
                block1_list11: '星空情境燈光',
                block1_list1_txt: '以舒適體驗和易用性為設計核心，搭配現代感及簡潔的線條外型；量身訂製的純羊毛椅套與天然皮革頭枕，給您無與倫比的觸感享受。',
                block1_list2_txt: '航程中想使用的個人物品得以隨手可得、隨時取用。',
                block1_list3_txt: '單片非折疊式的桌面及旋轉式結構設計，更易於操作。大尺寸桌面結合側邊檯面的設計，更靈活滿足用餐或工作的空間需求。',
                block1_list4_txt: '搭載全球最新的eX3機上數位娛樂系統，享受專屬且奢華的娛樂體驗。',
                block1_list5_txt: '整合電源插座和遙控器，直覺式的符號設計與最適按鈕尺寸，讓面板使用更易上手。',
                block1_list6_txt: '安裝在較低的側邊位置，更易於平躺時使用。',
                block1_list7_txt: '座椅側邊的專屬閱讀燈，提供最舒適的閱讀及休憩環境。',
                block1_list8_txt: '創造個人的隱私空間。',
                block1_list9_txt: '以巧妙且柔和的燈光變化，打造自己喜愛的氛圍。',
                block1_list10_txt: '走道外側的資訊面板顯示座位號碼，並可呈現座椅是否符合起降模式、及請勿打擾的狀態。',
                block1_list11_txt: '全球首家於787安裝星空燈光，淡藍色結合星光燈營造夜晚星空。',
                block2_list1: '可調式頭頸支撐',
                block2_list2: '12吋 FULL HD螢幕',
                block2_list3: '電源插座',
                block2_list4: '寬敞座位空間',
                block2_list5: '情境式設計客艙燈光',
                block2_list1_txt: '座椅頭靠上下調整幅度達6英吋，並搭配6個方向調整角度及頸部支撐設計，滿足乘客不同身高的需求。',
                block2_list2_txt: '搭載全球最新的eX3機上數位娛樂系統，享受高品質視聽娛樂。',
                block2_list3_txt: '適用各類AC插頭，無論是處理公務或享受影音娛樂，皆能充分利用。(除第一排座位，其他均為3個座位配備2個插座)',
                block2_list4_txt: '德國RECARO座椅超薄結構設計，提供更寬敞舒適的乘坐體驗。',
                block2_list5_txt: '用餐時，琥珀色燈光營造浪漫燭光氛圍；休息時，柔和的轉場燈光，搭配藍色天際線與閃爍星空；不同情境模式燈光創造最放鬆的機艙環境。',
            },
            btn_close: "關閉",
        }
    },

    jp: {
        message: {
            hello: 'こんにちは、世界'
        },
        nav: {
            title1: '天空のスマイル',
            title2: '新型機の特徴',
            title3: '新体験',
            title4: '各客室クラス設備',
            title5: '映像紹介',
            title6: '抽獎活動',
        },
        index: {
            title: '妳好',
            kv_tw_sun: "../images/jp-sun.png",
            kv_tw_air: "../images/jp-air.png",
            kv_tw_water: "../images/jp-water.png",
            kvslogn_tw: "../images/kv-jp-slogn.png",
            about: {
                title1: '更多長榮787夢幻客機介紹',
                title2: '天空から舞い降りたドリームライナー',
                btn1: '外型介紹',
                btn2: '360°介紹',
                txt: 'ボーイング787型機は、最先端の空気動力テクノロジー、より軽量な複合材料及び最新コンピュータシステムを用いて、お客様一人一人に最も快適な空の旅を提供します。',
                list_title1: 'スマイルカーブの翼',
                list_title2: '飛行の安定性を強化',
                list_title3: '騒音を軽減する鋸歯状エンジンカバー',
                list_title4: '省エネと二酸化炭素排出削減',
                list_txt1: '翼には、軽くて薄く強靭な「炭素繊維複合材」を使用しています。これにより、これまでの旅客機の翼に比べ、より激しい気流の変化に耐えることができます。また、翼の先端は後方に向かってカーブし飛行時の空気抵抗を減少させるので、燃費もさらに改善されました。',
                list_txt2: '柔軟性のある炭素繊維複合材の翼により、従来の旅客機に比べ、不安定な気流によって生じる影響を緩和します。また、垂直風切り抑制システムを装備し、乱気流を検知すると翼を自動的に調整し、客室の揺れを軽減、飛行時の安定性を大幅に向上させました。',
                list_txt3: '最新型エンジンカバー(CHEVRON)を採用し、エンジンの冷熱気流混合プロセスをさらにスムーズにして、飛行中に生じる気流の騒音を効果的に軽減しました。',
                list_txt4: 'より軽量な複合材の使用で、機体重量の軽量化を効果的に実現しました。さらに、高性能のGenxエンジンを装備することで、これまでの旅客機に比べ20～25％燃費が向上し、二酸化炭素排出量も減少させています。',
            },
            feature: {
                title1: '新体験',
                front_title1: '../images/pic-jp-sun.png',
                front_title2: '../images/pic-jp-air.png',
                front_title3: '../images/pic-jp-water.png',
                front_txt1: '業界最大規模を誇る大きさの窓は、明るさが5段階に調整できる電子シェードを採用しており、思いのままに機外の絶景をお楽しみいただけます。',
                front_txt2: '従来機の機内気圧は海抜8,000フィートだったのに対し、新型機は海抜6,000フィートの気圧に調整可能な為、お客様の血液中の酸素量を高めて飛行機酔いなどの体調不良を軽減します。',
                front_txt3: '機体には耐久性に優れた炭素繊維複合材を採用し、客室内の湿度を従来より4倍近く引き上げ、乾燥による不快感を和らげます。',
                back_title1: '更大的舷窗面積',
                back_title2: '液晶體調節進光',
                back_title3: '更有效控制艙壓',
                back_title4: '機艙更保濕',
                back_txt1: '787採用業界最大面積舷窗，較A350增加40%、A330增加78%的窗戶面積，增加飛行時的採光及視野。',
                back_txt2: '不需遮陽板，只要透過按鈕，即可5段式調校窗戶顏色與進光量、減少窗外射入的眩光。',
                back_txt3: '相較傳統民航機艙壓在海拔8,000呎，787機身材質可將艙壓控制在海拔6,000呎，有助於減輕暈機不適，並提高血液含氧量。',
                back_txt4: '傳統民航機採用鋁合金材質，容易在濕潤的環境下產生腐蝕，所以會將機艙濕度保持在約4~7%，以增加機身使用壽命；787機身由於採用抗腐蝕的複合材質，能提升機艙濕度高達10~15%。',
            },
            classinfo: {
                title1: '機内設備',
                btn1: 'Royal Laurel Class',
                btn2: 'Economy Class',
                block1_title1: '全く新しいロイヤルローレルクラスを展開',
                block1_title2: '刷新されたビジネスクラスの客室',
                block1_title3: '斬新でカスタマイズされた座席',
                block1_title4: 'モダンな色彩の組合せ',
                block1_txt1: '全新長榮航空波音787皇璽桂冠艙，跨界攜手 BMW Designworks首席設計師，以空間、品牌為理念核心，跳脫傳統印象，客製化座椅環境從水平化設計出發，以現代色系與編織材質調和艙內視覺，打造寬達23吋的全平躺座椅。',
                block1_txt2: '従来の客室デザインからの脱却を図り、広々とした空間および他に類を見ない寛ぎをテーマとして、お客様一人一人のニーズに合わせてカスタマイズすることのできる座席を客室の雰囲気に調和させ、落ち着いた色彩で客室内をより広く感じさせています。',
                block1_txt3: '座席はゆっくりおくつろぎいただける空間を重視し、かつ、お客様のプライバシーやサービス時の利便性および収納スペースを考慮して設計されており、あらゆる面においてお客様のニーズを満たします。',
                block1_txt4: '快適さを追求し最高級の材質を使用した座席は、美しい色彩に彩られ現代アートのような上質感をも兼ね備えています。',
                block1_list1: 'フルフラットスタッガード配列座席',
                block1_list2: 'パーソナル手荷物収納スペース',
                block1_list3: '大型テーブル',
                block1_list4: '18インチ フルHDスクリーン',
                block1_list5: '座席コントロールパネル',
                block1_list6: '座席サブコントロールパネル',
                block1_list7: '読書灯',
                block1_list8: '可動式仕切り板',
                block1_list9: 'ムードライト',
                block1_list10: '表示パネル',
                block1_list11: '星空ムード照明',
                block1_list1_txt: 'モダンかつシンプルさを追求した設計で、お客様一人一人の快適さ及び使い易さに配慮しています。特注の高品質純羊毛シートカバーやレザー製のヘッドレストは、お客様にこの上ない快適さを感じていただけます。',
                block1_list2_txt: '飛行中、お客様のお好きな時にお荷物を出し入れすることができます。',
                block1_list3_txt: '折り畳み式ではない1枚板のテーブルは回転式となっており、さらに使い易くなりました。サイドテーブルと組み合わせることで、お客様のお食事や作業がよりスムーズかつ快適になります。',
                block1_list4_txt: '世界最新のeX3機内デジタルエンターテインメントシステムを搭載し、18インチフルHDタッチ式LCDパネルを通して、自分専用の豪華な機内エンターテインメントをお楽しみいただけます。',
                block1_list5_txt: '電源コンセントとリモコンを内臓したコントロールパネルは、直感的に操作でき 押しやすい大きさのアイコンを採用し、シンプルかつ使いやすいデザインとなっています。',
                block1_list6_txt: '座席サブコントロールパネルは比較的低い側面に取付けてあり、お客様がシートを倒した状態でも使いやすくなっています。',
                block1_list7_txt: '座席横の読書灯は、読書やくつろぎに最適な環境を提供します。',
                block1_list8_txt: 'お客様専用のプライベートな空間を作ります。',
                block1_list9_txt: '柔らかな光の絶妙な変化によって、ゆったりと寛ぐことができます。',
                block1_list10_txt: '通路側の表示パネルには座席番号、座席が離着陸モードになっているか、また、「Do Not Disturb」表示が選択でき、お休みになりたいお客様に配慮したサービスを提供することができます。',
                block1_list11_txt: '世界で初めて787型機に星空ムード照明を設置し、ブルーライトに星空モードを組み合わせ、夜の星空を再現します。',
                block2_list1: '可動式ヘッド＆ネックサポート',
                block2_list2: '12インチ フルHDスクリーン',
                block2_list3: '電源コンセント',
                block2_list4: '広い座席スペース',
                block2_list5: 'シーンに合わせた客室照明',
                block2_list1_txt: '上下調節幅が6インチあるヘッドレストや、6方向に角度を調整できるネックサポートは、身長の異なる全てのお客様にぴったりフィットするので、お客様一人一人に満足していただけるものになっています。',
                block2_list2_txt: '世界最新を誇るeX3機内デジタルエンターテインメントシステムは、自分専用の豪華な機内エンターテインメントをお楽しみいただけます。',
                block2_list3_txt: '各種ACプラグに対応しています。ビジネスやエンターテインメント用に限らず、自由にご利用いただけます。(1列目を除き、3座席毎にコンセントが2個配備されています。)',
                block2_list4_txt: 'ドイツRECARO社の超薄型設計の座席は、広くて快適な座席スペースを提供します。',
                block2_list5_txt: 'お食事時には琥珀色の灯りがロマンチックな気分を醸し出します。お休み時にはやわらかな灯りが場面転換効果を演出し、青い地平線ときらめく星空に合わせ、客室を最もリラックスできる休憩スペースにします。',
            },
            btn_close: "閉じる",
        }
    },
}

const lang = checkLang();

function checkLang() {
    var langs = ['en', 'zh_tw', 'jp'],
        langx;
    for (var i = 0; i < langs.length; i++) {
        if (location.href.indexOf('/' + langs[i] + '/') != -1) {
            langx = i;
        }
    }
    return langs[langx];
}
// Create VueI18n instance with options
const i18n = new VueI18n({
    locale: lang, // set locale
    messages
})

// Create a Vue instance with `i18n` option
